organisation:
  name: Coventry and Warwickshire Partnership NHS Trust
  email: # Contact email address
  phone: # Contact phone number
  ods_code: RYG
  careplus_venue_code: CWPTSI
  privacy_policy_url: https://www.covwarkpt.nhs.uk/download.cfm?ver=8286
  reply_to_id: ddc407a3-dda9-4183-be83-1309562c95b1

programmes: [hpv]

teams:
  coventry:
    name: Coventry School-Aged Immunisation Service
    email: Bewise.Immunise@covwarkpt.nhs.uk
    phone: # Contact phone number
  north_warwickshire:
    name: North Warwickshire School-Aged Immunisation Service
    email: NorthImms@covwarkpt.nhs.uk
    phone: # Contact phone number
  south_warwickshire:
    name: South Warwickshire School-Aged Immunisation Service
    email: SouthImms@covwarkpt.nhs.uk
    phone: # Contact phone number

schools:
  coventry:
    - 141939
    - 103751
    - 103760
    - 139292
    - 134269
    - 150498
    - 141376
    - 140958
    - 149424
    - 131574
    - 141992
    - 146436
    - 137209
    - 136126
    - 103747
    - 142960
    - 140366
    - 135335
    - 141104
    - 137272
    - 147346
    - 103750
    - 142339
    - 137225
    - 140248
    - 138023
    - 140961
    - 134970
  north_warwickshire:
    - 145019
    - 149580
    - 141277
    - 148398
    - 139936
    - 139468
    - 134464
    - 144764
    - 142881
    - 136595
    - 125777
    - 141836
    - 125764
    - 136986
    - 137079
    - 148828
    - 136158
    - 136459
    - 139937
    - 148243
    - 148554
    - 137597
    - 149916
    - 145224
  south_warwickshire:
    - 137172
    - 136622
    - 125774
    - 137770
    - 147345
    - 145470
    - 137766
    - 125805
    - 136963
    - 136991
    - 146697
    - 147432
    - 137302
    - 125788
    - 148429
    - 136907
    - 142202
    - 136510
    - 125787
    - 138767
    - 143905
    - 143634
    - 137235
    - 137236
    - 136786
    - 125775
    - 148362
    - 144633
    - 148032
    - 125781
    - 145486

clinics:
  team1:
    - name: # Name of the clinic
      address_line_1: # First line of the address
      address_town: # Town of the address
      address_postcode: # Postcode of the address
      ods_code: # Unique ODS code
