organisation:
  name: Norfolk, Suffolk and Cambridgeshire and Peterborough Community and School Age Immunisation Service (With existing sessions)
  email: hct.csaiscambspb@nhs.net
  phone: 0300 555 5055
  ods_code: RY4-2
  careplus_venue_code: UNUSED
  privacy_policy_url: https://www.hct.nhs.uk/privacy

programmes: [hpv]

teams:
  generic:
    name: Norfolk, Suffolk and Cambridgeshire and Peterborough Community and School Age Immunisation Service (With existing sessions)
    email: hct.csaiscambspb@nhs.net
    phone: 0300 555 5055

users:
  - email: nurse.ry4@example.com
    password: nurse.ry4@example.com
    given_name: Nurse
    family_name: RY4

schools:
  generic:
    # - 110861 # These are used by the main organisation
    # - 110862
    # - 110867
    # - 110907
    # - 110910
    # - 110923
    # - 110924
    # - 110925
    # - 110926
    # - 131205
    # - 135263
    # - 135739
    # - 135980
    # - 136266
    # - 136398
    # - 136580
    # - 136610
    # - 136992
    # - 137082
    # - 137248
    # - 137867
    # - 138053
    - 139082
    - 139408
    - 142902
    - 145051
    - 146369

# !IMPORTANT! The ODS codes of these clinics are not correct.

clinics:
  generic:
    - name: North Cambridgeshire Hospital
      address_line_1: Churchill Road
      address_town: Wisbech
      address_postcode: PE13 3AB
      ods_code: PE133AB2
