name: Continuous Deployment
run-name: Continuous Deployment of ${{ github.ref }} to environment "copilotmigration"
on:
  workflow_dispatch: # TODO remove before merging
  push:
#    branches: [ "main" ] # Uncommented to register workflow with github initially
jobs:
  Test:
    uses: ./.github/workflows/test.yml
    with:
      github_sha: ${{ github.sha }}
  Build:
    uses: ./.github/workflows/build.yml
    with:
      github_sha: ${{ github.sha }}
    needs: Test
  Deploy:
    uses: ./.github/workflows/deploy_mavis.yml
    with:
      environment: "copilotmigration"
      image_tag: ${{ github.sha }}
    needs: Build
