name: Continuous deployment
run-name: >-
  ${{ github.event_name == 'workflow_dispatch'
      && format('Deployment of ${{ github.ref_name }} to {0}', inputs.environment)
      || 'Continuous deployment of ${{ github.ref_name }} to QA and Test' }} 

on:
  push:
    branches: [MAV-921_continuous_deployment_job]
  workflow_dispatch:
    inputs:
      environment:
        description: Deployment environment
        required: true
        type: choice
        options:
          - qa
          - poc
          - copilotmigration
          - test
          - preview
          - training
          - production

jobs:
  test:
    uses: ./.github/workflows/test.yml
  build-and-push-image:
    needs: test
    uses: ./.github/workflows/build-and-push-image.yml
  deploy-infrastructure:
    needs: test
    strategy:
      fail-fast: false
      matrix:
        environment: >-
          ${{ fromJSON(github.event_name == 'workflow_dispatch'
            && format('["{0}"]', inputs.environment)
            || '["qa", "test"]') }}
    uses: ./.github/workflows/deploy-infrastructure.yml
    with:
      environment: ${{ matrix.environment }}
  deploy-application:
    needs: [build-and-push-image, deploy-infrastructure]
    strategy:
      fail-fast: false
      matrix:
        environment: >-
          ${{ fromJSON(github.event_name == 'workflow_dispatch'
            && format('["{0}"]', inputs.environment)
            || '["qa", "test"]') }}
    uses: ./.github/workflows/deploy-application.yml
    with:
      environment: ${{ matrix.environment }}
