name: Continuous deployment
run-name: Continuous deployment of ${{ github.ref_name }} to QA and Test

on:
  push:
    branches: [main]

jobs:
  test:
    uses: ./.github/workflows/test.yml
  build-and-push-image:
    needs: test
    uses: ./.github/workflows/build-and-push-image.yml
  deploy-infrastructure:
    needs: test
    strategy:
      fail-fast: false
      matrix:
        environment: [qa, test]
    uses: ./.github/workflows/deploy-infrastructure.yml
    with:
      environment: ${{ matrix.environment }}
  deploy-application:
    needs: [build-and-push-image, deploy-infrastructure]
    strategy:
      fail-fast: false
      matrix:
        environment: [ qa, test ]
    uses: ./.github/workflows/deploy-application.yml
    with:
      environment: ${{ matrix.environment }}
